export const GET_EXPENSE_TYPE = "GET_EXPENSE_TYPE";
export const ADD_EXPENSE_TYPE = "ADD_EXPENSE_TYPE";
export const UPDATE_EXPENSE_TYPE = "UPDATE_EXPENSE_TYPE";
export const DELETE_EXPENSE_TYPE = "DELETE_EXPENSE_TYPE";

export const GET_EXPENSE = "GET_EXPENSE";
export const ADD_EXPENSE = "ADD_EXPENSE";
export const DELETE_EXPENSE = "DELETE_EXPENSE";
export const UPDATE_EXPENSE = "UPDATE_EXPENSE";